#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
filter=""
dry="0"

while [[ $# > 0 ]]; do
    if [[ $1 == "--dry" ]]; then
        dry="1"
    else
        filter="$1"
    fi
    shift
done

log() {
    if [[ $dry == "1" ]]; then
        echo "[DRY_RUN]: $@"
    else
        echo "$@"
    fi
}

execute() {
    name=$(basename $1)
    log "stow --no-folding -t ~/ -d ./config $name"
    if [[ $dry == "1" ]]; then
        return
    fi
    stow --no-folding -t ~/ -d ./config $name
}

cd $script_dir
scripts=$(find ./config -maxdepth 1 -mindepth 1 -type d)

for script in $scripts; do
    if echo "$script" | grep -qv "$filter"; then
        log "filtering $script"
        continue
    fi

    execute $script
done
