# ==================================================================
# HYPRLAND CONFIGURATION HUB
# ==================================================================

# Temas e Cores (Seu arquivo existente)
source = ~/.config/hypr/conf/rose-pine.conf

# Módulos do Sistema
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/programs.conf
source = ~/.config/hypr/conf/autostart.conf

# Aparência e Comportamento
source = ~/.config/hypr/conf/appearance.conf
source = ~/.config/hypr/conf/input.conf

# Interação e Regras
source = ~/.config/hypr/conf/keybinds.conf
source = ~/.config/hypr/conf/rules.conf
