hl.on("hyprland.start", function()
    hl.exec_cmd("uwsm app -- quickshell")
    hl.exec_cmd("uwsm app -- hyprpaper")
    hl.exec_cmd("uwsm app -- hypridle")
    hl.exec_cmd("uwsm app -- hyprsunset")
    hl.exec_cmd("wl-paste --watch cliphist store")
end)
