format = """
$os\
$directory\
$git_branch\
$git_status\
$c\
$cpp\
$rust\
$lua\
$golang\
$nodejs\
$java\
$python\
$line_break$character"""

[c]
symbol = " "
format = '\[[$symbol($version(-$name))]($style)\]'

[cpp]
disabled = false
symbol = " "
format = '\[[$symbol($version(-$name))]($style)\]'

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "
format = '\[[$symbol$context]($style)\]'

[git_branch]
symbol = " "
format = '\[[$symbol$branch]($style)\]'

[golang]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[hostname]
ssh_symbol = " "

[java]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[lua]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[nodejs]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[os]
disabled = true
style = "fg:#9ccfd8"
format = '[$symbol]($style)'

[package]
symbol = "󰏗 "
format = '\[[$symbol$version]($style)\]'

[python]
symbol = " "
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[rust]
symbol = "󱘗 "
format = '\[[$symbol($version)]($style)\]'

[zig]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[cmake]
format = '\[[$symbol($version)]($style)\]'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[username]
format = '\[[$user]($style)\] '

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
