# colors.toml é gerado por `theme set`.
[general]
import = ["~/.config/alacritty/colors.toml"]

[window]
padding = { x = 35, y = 5 }

[font]
size = 12.0

normal = { family = "HackNerdFont" }

[mouse]
hide_when_typing = true

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_timeout = 0
blink_interval = 650
