input {
    kb_layout = br, gr
    kb_variant =
    kb_model =
    kb_options = grp:win_space_toggle
    # kb_options = grp:win_space_toggle
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    scroll_factor = 1

    repeat_delay = 300
    accel_profile = flat

    touchpad {
        natural_scroll = true
        scroll_factor = 0.4
    }
}

gesture = 3, horizontal, workspace

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
