windowrule {
    name = pavucontrol_window
    match:class = ^(org.pulseaudio.pavucontrol)$

    float = on
    size = 1000 650
    center = on
}

windowrule {
    name = nm-connection-editor_window
    match:class = ^(nm-connection-editor)$

    float = on
    size = 900 500
    center = on
}

windowrule {
    name = biblioteca_window
    match:title = ^Biblioteca$

    float = on
    size = 1000 650
    center = on
}

windowrule {
    name = figure_window
    match:title = ^Figure [0-9]

    float = on
    size = 1000 800
    center = on
}

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    name = clipse_window
    match:class = (com.example.clipse)

    float = on
    size = 800 500
    stay_focused = on
    center = on
}

windowrule {
    name = gimp_window
    match:class = (gimp)

    float = on
    size = 1280 720
    center = on
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

windowrule {
    name = satty_window
    match:class = ^(com\.gabm\.satty)$

    float = on
    size = 1200 800
    center = on
    stay_focused = on
}

# workspace=1, monitor:eDP-1, persistent:true, default:true
# workspace=2, monitor:HDMI-A-1, persistent:true, default:true
