add_newline = true
command_timeout = 200
continuation_prompt = '[❯❯](gold) '
format = " [$python$directory$git_branch$git_status]($style)$line_break $character"

palette = "rose_pine"

[palettes.rose_pine]
rose  = "#ebbcba"
pine  = "#31748f"
foam  = "#9ccfd8"
iris  = "#c4a7e7"
love  = "#eb6f92"
gold  = "#f6c177"
text  = "#e0def4"
muted = "#6e6a86"

[character]
error_symbol = "[✗](bold love)"
success_symbol = "[❯](bold gold)"

[python]
format = "[$symbol$virtualenv]($style) "
style = "italic muted"
symbol = ""

detect_extensions = []
detect_files = []
detect_folders = []

[directory]
use_logical_path = false
truncation_length = 2
truncation_symbol = "…/"
style = "bold foam"
repo_root_style = "bold pine"
read_only_style = "muted"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$branch]($style) "
style = "iris"

[git_status]
format     = "([$all_status]($style) )"
style      = "rose"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = "[](muted) "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""

[profiles]
transient = "$character"
